### ISSUE TITLE
Hi Steve, thanks for this sharing !

### ISSUE THREAD

**Issue by bluetyphoon77** [stevob14/cryptosignals#2]
I was searching for examples of little bots using free api's rather than binance or any exchange where kyc is needed.
I would love to ask you, how many lines would it take to write a script just printing a signal when BTCUSDT weekly RSI reached a specific level ? I'm a beginner and I would love to start with the most minimalistic script possible using Ta-lib or paprika :)
Would you be able to help ? I'd be ok to pay you for the writing of those lines... Please keep in touch ;)
thanks in advance

**Comment by stevob14** [comment]
That shouldn't take long as most of the logic to do what you would need is written in this particular script. Would you want the script to run continuously and alert when conditions are met?

**Comment by bluetyphoon77** [comment]
Hi Steve, thanks for your answer :)
But is it possible to get STOCHRSI, and ADXDI data too with this api ?
Yes, but the checks would be only once or 2 times per day ;) so very relaxed ;)
We can talk in PM if you are ok, about hiring your services maybe ;)

**Comment by stevob14** [comment]
I was able to write a pretty small script using ta-lib for minimalistic approach. I also updated it to use various exchanges by importing ccxt library. ADX, Stoch RSI(14) and RSI(14) - results appear to be similar to TradingView dependent upon the timeframe used. I wrote up some generalized signal parameters that can be changed upon request. Let me know if you're interested.

**Comment by bluetyphoon77** [comment]
Great Steve ! Thanks for this self-move of coding something quickly, and share what you did !
Can we keep in touch on telegram or mail ? Would be great to test it and maybe improve together. ;)

**Comment by stevob14** [comment]
stevob144 at gmail dot com

**Comment by stevob14** [comment]
that shouldn’t be too hard to do. how often would you want the program to check bitcoins rsi value?

**Comment by bluetyphoon77** [comment]
Hi Steve,
I had changes in my life and went away from internet for some time. Sorry 
for my delayed answer.
I would love to work together on the creation of a little script by adding 
stuff to yours if you are OK to work on it. Please give me your rates?
And I will learn python all along.
Because I never find someone good enough for what I need, even though it is 
super simple
Devs love to complicate stuff.
And your script seems a simple one like I love.
Would you be OK to work together on it?
Thanks
